# name: Sync with upstream

# on:
#   schedule:
#     - cron: '0 */6 * * *'
#   workflow_dispatch:

# jobs:
#   sync:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2
#       with:
#         ref: master
#     - name: Fetch upstream
#       run: git remote add upstream https://github.com/ORIGINAL_OWNER/ORIGINAL_REPOSITORY.git
#     - name: Sync with upstream
#       env:
#         GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
#       run: |
#         git fetch upstream
#         git checkout master
#         git merge upstream/master
#         git push
